// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_config/network_helper.proto

package network_helper

import proto "Kademlia---P2P-DFS/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type SayHelloWorld struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloWorld) Reset()         { *m = SayHelloWorld{} }
func (m *SayHelloWorld) String() string { return proto.CompactTextString(m) }
func (*SayHelloWorld) ProtoMessage()    {}
func (*SayHelloWorld) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9a1501f19acc56d, []int{0}
}
func (m *SayHelloWorld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloWorld.Unmarshal(m, b)
}
func (m *SayHelloWorld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloWorld.Marshal(b, m, deterministic)
}
func (m *SayHelloWorld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloWorld.Merge(m, src)
}
func (m *SayHelloWorld) XXX_Size() int {
	return xxx_messageInfo_SayHelloWorld.Size(m)
}
func (m *SayHelloWorld) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloWorld.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloWorld proto.InternalMessageInfo

func (m *SayHelloWorld) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Package struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9a1501f19acc56d, []int{1}
}
func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Package) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Package) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Package) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*SayHelloWorld)(nil), "network_helper.SayHelloWorld")
	proto.RegisterType((*Package)(nil), "network_helper.Package")
}

func init() { proto.RegisterFile("proto_config/network_helper.proto", fileDescriptor_e9a1501f19acc56d) }

var fileDescriptor_e9a1501f19acc56d = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0xcf, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca,
	0x8e, 0xcf, 0x48, 0xcd, 0x29, 0x48, 0x2d, 0xd2, 0x03, 0xcb, 0x09, 0xf1, 0xa1, 0x8a, 0x2a, 0x29,
	0x73, 0xf1, 0x06, 0x27, 0x56, 0x7a, 0xa4, 0xe6, 0xe4, 0xe4, 0x87, 0xe7, 0x17, 0xe5, 0xa4, 0x08,
	0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x4a, 0xd1, 0x5c, 0xec, 0x01, 0x89, 0xc9, 0xd9, 0x89, 0xe9, 0xa9, 0x42, 0x7c, 0x5c, 0x4c, 0x99,
	0x29, 0x50, 0x49, 0xa6, 0x4c, 0xb0, 0xf2, 0x92, 0xca, 0x82, 0x54, 0x09, 0x26, 0x88, 0x72, 0x10,
	0x5b, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x19, 0x2c, 0x0c,
	0xe3, 0x82, 0x55, 0x67, 0xe6, 0xa6, 0x4a, 0xb0, 0x40, 0x55, 0x67, 0xe6, 0xa6, 0x26, 0xb1, 0x81,
	0x1d, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x13, 0x5f, 0x76, 0x43, 0xbd, 0x00, 0x00, 0x00,
}
